### ISSUE TITLE
Ingestion of CaSPAr data products

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#36] opened 2019-03-29 15:35 UTC
Let's ingest all the CaSPAr products and let @julemai start playing with the current demo.

**Comment by julemai** [comment] 2019-03-29 15:43
Sounds good. We can work on that when I’m back from conference on April 15.

**Comment by gauchm** [comment] 2019-07-08 15:37
Closing as duplicate of #63.

**Closed by gauchm** 2019-07-08 15:37 UTC
